version: 2

jobs:
  deploy:
    working_directory: ~/scala-aws-batch-sample
    docker:
    - image: openjdk:8
    environment:
      SBT_VERSION: 1.2.8
    steps:
    - checkout
    - restore_cache:
        key: sbt-cache
    - setup_remote_docker
    - run:
        name: SBT Install
        command: |
          apt update && apt install -y curl
          curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
          dpkg -i sbt-$SBT_VERSION.deb
          rm sbt-$SBT_VERSION.deb
          apt-get update
          apt-get install -y sbt python-pip git
          pip install awscli
          apt-get clean && apt-get autoclean
    - run:
        name: Compile
        command: sbt clean update compile
    - run:
        name: Docker login
        command: $(aws ecr get-login --region ap-northeast-1)
    - run:
        name: Publish container image (scala-aws-batch-sample)
        command: sbt docker:publish

workflows:
  version: 2
  main:
    jobs:
      - deploy