version: 2.1

jobs:
  deploy:
    working_directory: ~/scala-aws-batch-sample
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.2.8
    steps:
    - checkout
    - restore_cache:
        key: sbt-cache
    - setup_remote_docker
    - run:
        name: SBT Install
        command: |
          sudo apt-get install -y \
          python \
          python-pip \
          && sudo pip install awscli \
         && $(aws ecr get-login --region ap-northeast-1 --no-include-email)
    - run:
        name: Compile
        command: sbt clean update compile
    - run:
        name: Docker login
        command: $(aws ecr get-login --region ap-northeast-1)
    - run:
        name: Publish container image (scala-aws-batch-sample)
        command: sbt docker:publish

workflows:
  version: 2
  main:
    jobs:
      - deploy